"""add image_url to fairs

Revision ID: 6b0754765a92
Revises: 8d4e1973b768
Create Date: 2026-06-28 16:07:14.498821+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6b0754765a92"
down_revision: Union[str, Sequence[str], None] = "8d4e1973b768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fairs", sa.Column("image_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fairs", "image_url")
    # ### end Alembic commands ###
